apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: simple-client-go-pod-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: simple-client-go-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: simple-client-go-pod-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
